### ISSUE TITLE
Where's the Dockerfile?

### ISSUE THREAD

**Issue by passsy** [jxstxn1/dockerize_sidekick_plugin#27]
I'm running into this issue:

```
❯ pq docker build

💪 Building with sound null safety 💪

Compiling lib/main.dart for the Web...                             611ms
Creating image pascalq:dev
#1 [internal] load build definition from Dockerfile
#1 sha256:17c9e5d4c11bbfb110f145503ae2b7eff73a9f7544b4c33cd2552626af636148
#1 transferring dockerfile: 2B done
#1 DONE 0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount362344577/Dockerfile: no such file or directory

Usage: You can execute the following commands:
• pq docker
   • build               Builds your project and the docker container
   • run                 Runs the Docker Container on localhost:8000
     -b, --build         Calls the build command before running the app
     -p, --port  Set a custom entry port for the container
   • stop                Stops the currently running docker container
```

Seems like I'm missing a Dockerfile, but I haven't found it. Any idea what to do?

**Comment by jxstxn1** [comment]
Can reproduce the multi package Bug.
The Docker File Error seems related to this Error because dockerize is probably unable to find the File.

**Comment by jxstxn1** [comment]
> My repo looks like this:
> 
> - flutter_app
> - pq_sidekick
> - server

So your Filestruture is like this:
```bash
packages
  - flutter_app
 - pq_sidekick
 - server
```

Can reproduce the multi package Bug. The Docker File Error seems related to this Error because dockerize is probably unable to find the File.

**Comment by passsy** [comment]
> So your Filestruture is like this:
> 
> ```shell
> packages
>   - flutter_app
>   - pq_sidekick
>   - server
> ```

No. I don't have a `packages` folder. All packages are located in the root of my repository

**Comment by jxstxn1** [comment]
Alright then we have to change the installation to only create the server folder in `packages` if the folder exists

**Comment by robiness** [comment]
Shouldn't this be a sidekick feature?
To figure where the packages are located? 

From a plugin perspective i want to find a package folder by name but do not implement it on my own.
I think sidekick should be aware of the structure rather than a plugin. Does that make sense @passsy ?
