### ISSUE TITLE
docker run should show output

### ISSUE THREAD

**Issue by passsy** [jxstxn1/dockerize_sidekick_plugin#30]
After running `<cli> docker run` I can't see the log. The process completes right away.

Instead, I expected to see the log output and to stop the docker container with `ctrl` + `C`.

To run it in the background I'd use `<cli> docker run &`

**Comment by jxstxn1** [comment]
Can you define the `<cli> docker run &` more in detail?

**Comment by passsy** [comment]
The `&` sign detaches the process from the terminal, [running it in the background](https://www.tecmint.com/run-linux-command-process-in-background-detach-process/).

It's just one way to run processes in the background. The default should be that `docker run` does not run in the background. Similar to `flutter run`.
