### ISSUE TITLE
Document how to release the docker container

### ISSUE THREAD

**Issue by passsy** [jxstxn1/dockerize_sidekick_plugin#31]
Currently, the container is tagged as `$package_name:dev`, overriding the old container.

I'd love to have some documentation how to tag the container with a `version`, i.e. the version from `pubspec.yaml` 

Or maybe create a new option for building `<cli> docker build --release`

**Comment by jxstxn1** [comment]
Thanks for the Issue
I will handle this in the documentation combined with #6 and #32. Is this fine for you?
